LDAP_DIR: "/opt/LDAP"
LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
LDAP_GROUP: "{{ ldap_cluster_prefix }}"
LDAP_USER: "{{ ldap_user_name }}"
LDAP_USER_PASSWORD: "{{ ldap_user_password }}"
BASE_DN: "{{ ldap_basedns }}"
LDAP_SERVER_IP: "{{ ldap_server }}"
LDAP_CERT_FILES_DIR: "/opt/IBM/ibm-spectrumscale-cloud-deploy/dap_key"