---
# YUM repository installation method

#
# Configure YUM repository
#
- name: install | Configure Grafana YUM repository
  yum_repository:
    name: spectrum-scale-grafana
    description: IBM Spectrum Scale (grafana)
    baseurl: "{{ scale_install_repository_url }}gpfs_rpms/"
    gpgcheck: "{{ scale_install_gpgcheck }}"
    repo_gpgcheck: no
    sslverify: no
    state: present
  notify: yum-clean-metadata
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - scale_install_repository_url is defined
    - scale_install_repository_url != 'existing'

- name: install | Configure Grafana APT repository
  apt_repository:
    filename: spectrum-scale-grafana-debs
    repo: "deb [trusted=yes] {{ scale_install_repository_url }}gpfs_debs/ ./"
    validate_certs: no
    state: present
    update_cache: yes
    codename: IBM Spectrum Scale (grafana debs)
    mode: 0777
  when:
    - ansible_pkg_mgr == 'apt'
    - scale_install_repository_url is defined
    - scale_install_repository_url != 'existing'

- name: install | Configure grafana repository
  zypper_repository:
    name: spectrum-scale-grafana
    description: IBM Spectrum Scale (grafana)
    repo: "{{ scale_install_repository_url }}gpfs_rpms/"
    disable_gpg_check: no
    state: present
    overwrite_multiple: yes
  when:
    - ansible_pkg_mgr == 'zypper'
    - scale_install_repository_url is defined
    - scale_install_repository_url != 'existing'

#
# Add grafana RPMs
#

- name: install | Add GPFS grafana package to list
  set_fact:
    scale_install_all_packages: "{{ scale_install_all_packages + [ item ] }}"
  with_items:
    - "{{ scale_grafana_packages }}"
  when: scale_install_package | bool
