---
# tasks file for cluster
- import_tasks: configure.yml
  when: scale_callhome_params is defined and (scale_callhome_params.is_enabled|bool or (not scale_callhome_params.is_enabled|bool))
  tags: config
