---
- name: upgrade | Initialize
  set_fact:
    disable_gpgcheck: "no"

- name: upgrade | Disable gpg check
  set_fact:
    disable_gpgcheck: "yes"
  when: scale_version < '5.0.5.0'

- name: upgrade | Install Scale object packages
  dnf:
   name: "{{ scale_install_all_packages }}"
   state: latest
   disable_gpg_check: "{{ disable_gpgcheck }}"
  when: ansible_pkg_mgr == 'dnf'
