---
# This file is mandatory to import and it will load scale 
# inventory variable form vars/scale_clusterdefinition.json.
- import_playbook: "set_json_variables.yml"

- hosts: scale_node
  vars:
    - scale_install_localpkg_path: /root/Spectrum_Scale_Advanced-5.1.0.0-x86_64-Linux-install
  roles:
     #- core/precheck
     #- core/node
     #- core/cluster
     #- gui/precheck
     #- gui/node
     #- gui/cluster
     #- gui/postcheck
     #- zimon/precheck
     #- zimon/node
     #- zimon/cluster
     #- zimon/postcheck
     #- callhome/precheck
     #- callhome/cluster
     - nfs/precheck
     - nfs/node
     - nfs/cluster
     - smb/node
     - smb/cluster
