---
# Install or update packages

#
# Install or update packages
#
- name: install | Initialize
  set_fact:
    scale_disable_gpgcheck: "no"

- name: install | Disable gpg check
  set_fact:
    scale_disable_gpgcheck: "yes"
  when: scale_version < '5.0.4.0'

- block:  ## when: not scale_daemon_running
    - block:
        - name: install | List installed GPFS packages
          yum:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_packagelist
          when: ansible_pkg_mgr == 'yum'

        - name: install | Get GPFS packages list
          set_fact:
             scale_install_all_packages: "{{ scale_install_all_packages + scale_install_license_packages }}"

        - name: install | Install GPFS packages
          yum:
            name: "{{ scale_install_all_packages }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_packageresult
          when: ansible_pkg_mgr == 'yum'

        - name: install | List installed GPFS packages
          dnf:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_dnfpackagelist
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Install GPFS packages
          dnf:
            name: "{{ scale_install_all_packages }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_dnfpackageresult
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
          when:
            - ("'installed' in scale_install_packagelist.results | map(attribute='yumstate') | list") or
              ("'installed' in scale_install_dnfpackagelist.results | map(attribute='yumstate' | list")
            - (scale_install_packageresult.changed) or (scale_install_dnfpackageresult.changed)
      when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
  when: not scale_daemon_running
