---
- name: Initialize
  set_fact:
    disable_gpgcheck: "no"

- name: Disable gpg check
  set_fact:
    disable_gpgcheck: "yes"
  when: scale_version < '5.0.4.4'

- name: install | Install GPFS HDFS packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ disable_gpgcheck }}"
  when: ansible_hostname in scale_protocol_nodes_list or ansible_fqdn in scale_protocol_nodes_list
