# Static Variables for Encryption

# Directory to store Key Protect files 
key_protect_dir: "/opt/key_protect"

# Key Protect Port
key_protect_port: "5696"

# Key Protect files path on Bootstrap node
key_protect_cert_files_dir: "/opt/IBM/ibm-spectrumscale-cloud-deploy/key_protect"

kp_resource_prefix: "{{ scale_cluster_clustername.split('.')[0] }}"

scale_command_path: "/usr/lpp/mmfs/bin/"
