---
- block:
      - name: create | Define Vdiskset
        vars:
          current_vs: "{{ item.1.vdisk | default('vs_' + (item.1.rg | regex_replace('\\W', '_')) | basename) }}"
          current_rg: "{{ item.1.rg }}"
          current_code: "{{ item.1.ec }}"
          current_bs: "{{ item.1.blocksize }}"
          current_size: "{{ item.1.Size }}"
        command: "{{ scale_command_path }}mmvdisk vs define --vs {{ current_vs }} --rg {{ current_rg }} --code {{ current_code }} --bs {{ current_bs }} --ss {{ current_size }}"
        register: scale_vs_define
        failed_when: scale_vs_define.rc != 0
        when:
          - item.1.vdisk is defined
          - item.1.rg is defined
          - item.1.ec is defined
          - item.1.blocksize is defined
          - item.1.Size is defined

      - name: create | Create Vdiskset
        vars:
          current_vs: "{{ item.1.vdisk | default('vs_' + (item.1.rg | regex_replace('\\W', '_')) | basename) }}"
        command: "{{ scale_command_path }}mmvdisk vs create --vs {{ current_vs }}"
        register: scale_vs_create
        failed_when: scale_vs_create.rc != 0
        when:
          - item.1.vdisk is defined

      - name: create | Add vdisks to desire filesystem
        debug:
          msg: Vdisks created, add them to your filesystem using mmadddisk
  rescue:
    - debug:
        msg: "I caught an error, Please take a look to the output given and refer to the Knowledge center!"
