---
- name: Install GPFS hdfs packages
  package:
   name: "{{ scale_install_all_packages }}"
   state: present
  when: scale_install_repository_url is defined and ansible_fqdn in scale_hdfs_nodes_list


- name: install| Install GPFS HDFS deb
  apt:
   deb: "{{ item }}"
   state: present
  when: scale_install_repository_url is not defined and ansible_fqdn in scale_hdfs_nodes_list
  with_items:
  - "{{ scale_install_all_packages }}"

