---
# Checking the filesystem is mounted or not

# Make default variables available in hostvars

- name: storage | Find existing filesystem
  shell: "{{ scale_command_path }}mmlsfs all -Y | grep -v HEADER | cut -d ':' -f 7 | uniq"
  register: scale_storage_existing_fs
  changed_when: false
  failed_when: false

- name: Encryption | Filesystem | Check
  shell: mount | grep -q "{{ scale_storage_existing_fs.stdout }}" && echo "mounted" || echo "not mounted"
  register: mount_status
  changed_when: false

- debug:
    msg: "Filesystem is {{ mount_status.stdout }}"