---
# Creating client for the storage cluster

# Make default variables available in hostvars

- name: Encryption | Creating Client
  shell: |
        echo -e "not_null\nnot_null" | {{ scale_command_path }}mmkeyserv client create "{{ scale_cluster_profile_name | replace('sncparams', '') }}" --server "{{ scale_encryption_servers[0] }}" --server-pwd "{{ password_file }}"
  register: create_client_output
  run_once: true

- debug:
    var: create_client_output.json