---
# Registering the client to the created tenant for the storage cluster

# Make default variables available in hostvars

- name: Encryption | Registering Client
  command: "{{ scale_command_path }}mmkeyserv client register {{ scale_cluster_profile_name | replace('sncparams', '') }} --rkm-id rkm_ClusterTenant1 --tenant {{ tenant_name }} --server-pwd {{ password_file }}"
  register: register_client_output
  run_once: true

- debug:
    var: register_client_output.stdout_lines
  