---
- name: check | GPFS base path for SLES
  set_fact:
    scale_gpfs_path_url: '{{ scale_extracted_path }}/gpfs_rpms'
  when:
    scale_install_localpkg_path is defined or
    scale_install_remotepkg_path is defined
