---
# Cleaning the secret files which are stored locally.

# Make default variables available in hostvars

- name: "************************ Encryption | Cleaning the SGKLM secret files ************************"
  file:
    path: "{{ sgklm_dir }}"
    state: absent
    recurse: false
  register: cleanup_output
  run_once: true

- debug:
    var: cleanup_output.stdout_lines
  when: cleanup_output is defined
