---
# Print messages collected during play

- block:  ## run_once: true
    - name: configure | check if package upgraded
      set_fact:
        scale_install_updated: true
      when:
        - hostvars[item].scale_install_updated is defined
        - true in ansible_play_hosts | map('extract', hostvars, 'scale_install_updated') | map('bool') | list
      with_items: "{{ ansible_play_hosts }}"
      run_once: true
      delegate_facts: true

    - name: configure | check if parameters were changed
      set_fact:
        scale_config_changed: true
      when:
        - hostvars[item].scale_config_changed is defined
        - true in ansible_play_hosts | map('extract', hostvars, 'scale_config_changed') | map('bool') | list
      with_items: "{{ ansible_play_hosts }}"
      run_once: true
      delegate_facts: true

    - name: finalize | Check if GPFS RPMs were updated
      vars:
        msg: |-
          ######################################################################
          Spectrum Scale packages were updated. Once all nodes in the cluster
          run the new version, consider updating configuration information to
          the latest format that is supported by the currently installed level:

            mmchconfig release=LATEST

          Furthermore, consider updating file systems to the latest format that
          is supported by the currently installed level:

            mmchfs fs1 -V full

          Remember that nodes in remote clusters running an older version will
          no longer be able to mount the file system!
          ######################################################################
      debug:
        msg: "{{ msg.split('\n') }}"
      when:
        - scale_install_updated is defined
        - scale_install_updated | bool

    - name: finalize | Check if configuration parameters were changed
      vars:
        msg: |-
          ######################################################################
          Configuration parameters were changed. Please restart Spectrum Scale
          on all nodes for the new settings to take effect!
          ######################################################################
      debug:
        msg: "{{ msg.split('\n') }}"
      when:
        - scale_config_changed is defined
        - scale_config_changed | bool
  run_once: true
