#Static Variables for Encryption

#Directory to store GKLM files
gklm_dir: "/opt/gklm"

#Tenant name
create_tenant_name: "{{ scale_cluster_clustername.split('.')[0] | regex_replace('-', '') | lower }}"
tenant_name: "{{ create_tenant_name[:16] }}"

#Password file for performing Encryption operations
password_file: "{{ gklm_dir }}/.gklm_pass"

# default mm command exection path
scale_command_path: /usr/lpp/mmfs/bin/