---
#
# Install or update RPMs
#
- name: install | Install GPFS file audit logging packages
  package:
    name: "{{ scale_install_all_packages }}"
    state: present
    disable_gpg_check: "{{ scale_disable_gpgcheck }}"
