---
# Task to setup the Auth

- name: Setup Auth
  shell: "{{ scale_command_path }}mmmuserauth service create --data-access-method file --type userdefined"
  run_once: true
  when: service_result.rc is defined and service_result.rc != 0
