---
# Install and configure IBM Spectrum Scale (GPFS)

- import_tasks: install.yml
  tags: install

- import_tasks: build.yml
  tags: build

- import_tasks: install_nodeid.yml 
  tags: install
  when:
    - scale_mos is defined
    - hostvars[inventory_hostname].node_cert is defined and hostvars[inventory_hostname].node_cert != "None"
    - hostvars[inventory_hostname].node_cert_key is defined and hostvars[inventory_hostname].node_cert_key != "None"
    - hostvars[inventory_hostname].node_cert_chain is defined and hostvars[inventory_hostname].node_cert_chain != "None"
