---
# Fixed error for evaluating conditional
# Install or update packages

#
# Install or update packages
#
- block:  ## when: not scale_daemon_running
    - block:
        - name: install | List installed GPFS packages
          yum:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) | bool }}"
          register: scale_install_packagelist
          when: ansible_pkg_mgr == 'yum'

        - name: install | Get GPFS packages list
          set_fact:
             scale_install_all_packages: "{{ scale_install_all_packages + scale_install_license_packages }}"

        - name: install | Install GPFS packages
          yum:
            name: "{{ scale_install_all_packages }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) | bool }}"
          register: scale_install_packageresult
          when: ansible_pkg_mgr == 'yum'

        - name: install | List installed GPFS packages
          dnf:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) | bool }}"
          register: scale_install_dnfpackagelist
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Install GPFS packages
          dnf:
            name: "{{ scale_install_all_packages }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) | bool }}"
          register: scale_install_dnfpackageresult
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
          when:
            - scale_install_packagelist is defined and scale_install_packagelist.results is defined and
              ("installed" in scale_install_packagelist.results | map(attribute='yumstate') | list)
            - scale_install_dnfpackagelist is defined and scale_install_dnfpackagelist.results is defined and
              ("installed" in scale_install_dnfpackagelist.results | map(attribute='yumstate') | list)
            - scale_install_packageresult.changed | default(false) | bool or scale_install_dnfpackageresult.changed | default(false) | bool
      when: ansible_pkg_mgr in ['yum', 'dnf']
  when: not scale_daemon_running | bool

- block:
     - name: install | Get scaleapi package
       command: rpm -qi gpfs.scaleapi
       register: package_name_scaleapi
       ignore_errors: true
       failed_when: false
       when:
         - ansible_pkg_mgr in ['yum', 'dnf']

     - name: install | Install GPFS scaleapi package
       dnf:
         name: "gpfs.scaleapi"
         state: present
       ignore_errors: true
       failed_when: false
       when:
          - package_name_scaleapi.rc is defined | bool
          - package_name_scaleapi.rc != 0
  when: scale_scaleadmd is defined | bool