---
# Install or update packages

#
# Install or update packages
#
- block:  ## when: not scale_daemon_running
    - block:
        - name: install | List installed GPFS packages
          yum:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) }}"
          register: scale_install_packagelist
          when: ansible_pkg_mgr == 'yum'

        - name: install | Get GPFS packages list
          set_fact:
             scale_install_all_packages: "{{ scale_install_all_packages | default([]) + scale_install_license_packages | default([]) }}"

        - name: install | Install GPFS packages
          yum:
            name: "{{ scale_install_all_packages | default([]) }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) }}"
          register: scale_install_packageresult
          when: ansible_pkg_mgr == 'yum'

        - name: install | List installed GPFS packages
          dnf:
            list: gpfs.base
            disablerepo: spectrum-scale-gpfs
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) }}"
          register: scale_install_dnfpackagelist
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Install GPFS packages
          dnf:
            name: "{{ scale_install_all_packages | default([]) }}"
            state: present
            disable_gpg_check: "{{ scale_disable_gpgcheck | default(false) }}"
          register: scale_install_dnfpackageresult
          when: ansible_pkg_mgr == 'dnf'

        - name: install | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
          when:
            - (scale_install_packagelist.results | map(attribute='yumstate') | list | select('eq', 'installed') | list | length > 0) or
              (scale_install_dnfpackagelist.results | map(attribute='yumstate') | list | select('eq', 'installed') | list | length > 0)
            - scale_install_packageresult.changed | default(false) or scale_install_dnfpackageresult.changed | default(false)
      when: ansible_pkg_mgr in ['yum', 'dnf']
  when: not scale_daemon_running

- block:
     - name: install | Get scaleapi package
       command: rpm -qi gpfs.scaleapi
       register: package_name_scaleapi
       ignore_errors: true
       failed_when: false
       when:
         - ansible_pkg_mgr in ['yum', 'dnf']

     - name: install | Install GPFS scaleapi package
       dnf:
         name: "gpfs.scaleapi"
         state: present
       ignore_errors: true
       failed_when: false
       when:
          - package_name_scaleapi.rc is defined
          - package_name_scaleapi.rc != 0
  when: scale_scaleadmd is defined
