---
- name: Initialize
  set_fact:
    disable_gpgcheck: "no"

- name: Disable gpg check
  set_fact:
    disable_gpgcheck: "yes"
  when: scale_version < '5.0.5.0'

- name: install | Install GPFS gnr packages
  yum:
   name: "{{ scale_install_all_packages }}"
   state: present
   disable_gpg_check: "{{ disable_gpgcheck }}"
