---
# YUM repository installation method

#
# Configure YUM repository
#
- name: upgrade | Initialize
  set_fact:
   gpgcheck: "yes"

- name: upgrade | Disable gpg check
  set_fact:
   gpgcheck: "no"
  when: scale_version < '5.0.4.0'

- name: upgrade | Configure HPT YUM repository
  yum_repository:
    name: spectrum-scale-hpt
    description: IBM Spectrum Scale (HPT)
    baseurl: "{{ scale_install_repository_url }}gpfs_rpms/"
    gpgcheck: "{{ gpgcheck }}"
    repo_gpgcheck: no
    sslverify: no
    state: present
  notify: yum-clean-metadata
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - scale_install_repository_url != 'existing'

- name: upgrade | Configure HPT APT repository
  apt_repository:
    filename: spectrum-scale-hpt-debs
    repo: "deb [trusted=yes] {{ scale_install_repository_url }}gpfs_debs/ ./"
    validate_certs: no
    state: present
    update_cache: yes
    codename: IBM Spectrum Scale (HPT debs)
    mode: 0777
  when:
    - ansible_pkg_mgr == 'apt'
    - scale_install_repository_url != 'existing'

- name: upgrade | Configure HPT repository
  zypper_repository:
    name: spectrum-scale-hpt
    description: IBM Spectrum Scale (HPT)
    repo: "{{ scale_install_repository_url }}gpfs_rpms/"
    disable_gpg_check: no
    state: present
    overwrite_multiple: yes
  when:
    - ansible_pkg_mgr == 'zypper'
    - scale_install_repository_url != 'existing'

#
# Add HPT RPMs
#

- name: upgrade | Add GPFS AFM COS package to list
  set_fact:
    scale_install_all_packages: "{{ scale_install_all_packages + [ item ] }}"
  with_items:
    - "{{ scale_hpt_packages }}"
  when: scale_install_package | bool
