---
#
# Install or update packages
#
- block:  ## when: not scale_daemon_running
    - block:
        - name: install | dependencies package
          zypper:
            name: binutils
            state: present

        - name: install | Install GPFS packages
          zypper:
            name: "{{ scale_install_all_packages | default([]) }}"
            state: present
            disable_gpg_check: no
          register: scale_install_zypppackageresult

        - name: install | Install GPFS License packages
          zypper:
            name: "{{ scale_install_license_packages | default([]) }}"
            state: present
            disable_gpg_check: no
          register: scale_install_license_packageresult

        - name: install | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
          when:
            - scale_install_zypppackageresult.changed | default(false)
  when: not scale_daemon_running

- block:
     - name: install | Get scaleapi package
       command: rpm -qi gpfs.scaleapi
       register: package_name_scaleapi
       ignore_errors: true
       failed_when: false
       when:
         - ansible_pkg_mgr == 'zypper'

     - name: install | Install GPFS scaleapi package
       zypper:
         name: "gpfs.scaleapi"
         state: present
       ignore_errors: true
       failed_when: false
       when:
          - package_name_scaleapi.rc is defined
          - package_name_scaleapi.rc != 0
  when: scale_scaleadmd is defined
