---
#
# Install or update packages
#
- block:  ## when: not scale_daemon_running
    - block:
        - name: upgrade | dependencies package
          zypper:
            name: binutils
            state: present

        - name: upgrade | Upgrade GPFS packages
          zypper:
            name: "{{ scale_install_all_packages }}"
            state: latest
            disable_gpg_check: no
          register: scale_install_zypppackageresult

        - name: upgrade | Upgrade GPFS License packages
          zypper:
            name: "{{ scale_install_license_packages }}"
            state: latest
            disable_gpg_check: no
          register: scale_install_license_packageresult

        - name: upgrade | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
          when:
            - (scale_install_zypppackageresult.changed)
  when: not scale_daemon_running
