galaxy_info:
  role_name: remote_mount
  author: IBM Corporation
  description: IBM Spectrum Scale (GPFS) ansible role to configure remote mount
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8


  galaxy_tags: []

dependencies: []
