---

#
# Install or update RPMs
#
- name: upgrade | Upgrade GPFS file audit logging packages
  package:
    name: "{{ scale_install_all_packages }}"
    state: latest
  when: scale_install_repository_url is defined

- block:
    - name: upgrade | Upgrade GPFS file audit logging packages
      apt:
        deb: "{{ item }}"
        state: present
      with_items:
        - "{{ scale_install_all_packages }}"
  when: scale_install_repository_url is not defined
