---
# Dir package installation method

- block:  ## run_once: true
    - name: install | Stat directory installation package
      stat:
        path: "{{ scale_install_directory_pkg_path }}"
      register: scale_install_dirpkg

    - name: install | Check directory installation package
      assert:
        that: scale_install_dirpkg.stat.exists
        msg: >-
          Please set the variable 'scale_install_directory_pkg_path' to point to the
          local installation package (accessible on Ansible control machine)!
  run_once: true
  delegate_to: localhost

- name: install| Creates default directory
  file:
    path: "{{ scale_extracted_path }}"
    state: directory
    mode: a+x
    recurse: yes

- name: install | Stat extracted packages
  stat:
    path: "{{ scale_extracted_path + '/' + scale_install_directory_pkg_path | basename }}"
  register: scale_install_gpfs_packagedir

#
# Copy installation directory package to default
#
- block:
    - name: install | Copy installation package to node
      copy:
        src: "{{ scale_install_directory_pkg_path }}"
        dest: "{{ scale_extracted_path }}"
        mode: a+x

- name: install | Set installation package path
  set_fact:
    dir_path: "{{ scale_extracted_path + '/' + scale_install_directory_pkg_path | basename }}"

- name: install | gpfs base path
  set_fact:
    gpfs_path_url: "{{ dir_path }}"
  when: scale_install_directory_pkg_path is defined

#
# Find GPFS HDFS
#
# 

- block:  ## when: host is defined as a protocol node

  - name: install | Find gpfs.hdfs-protocol (gpfs.hdfs-protocol) package
    find:
     paths:  "{{ gpfs_path_url }}"
     patterns: gpfs.hdfs-protocol*
    register: scale_install_gpfs_hdfs

  - name: install | Check valid GPFS (gpfs.hdfs-protocol) package
    assert:
     that: scale_install_gpfs_hdfs.matched > 0
     msg: "No GPFS hdfs (gpfs.hdfs-protocol) package found {{ gpfs_path_url }}gpfs.hdfs-protocol*"

  - name: install | Add GPFS hdfs package to list
    vars:
     current_package:  "{{ item.path }}"
    set_fact:
     scale_install_all_packages: "{{ scale_install_all_packages + [ current_package ] }}"
    with_items:
    - "{{ scale_install_gpfs_hdfs.files }}"

- block:
  - name: initialize
    set_fact:
     debuginfo_package: []

  - name: install | Add GPFS package to list
    set_fact:
     debuginfo_package: "{{ debuginfo_package + [ item.path ] }}"
    with_items:
    - "{{ scale_install_gpfs_hdfs_debuginfo.files }}"

  - name: remove debuginfo from packages
    set_fact:
     scale_install_all_packages: "{{ scale_install_all_packages | difference(debuginfo_package)}}"
  when: not install_debuginfo|bool and ansible_distribution in scale_rhel_distribution

