LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
BASE_DN: "{{ ldap_basedns }}"
LDAP_SERVER_IP: "{{ ldap_server }}"
LDAP_CERT_FILES_DIR: "/opt/IBM/ibm-spectrumscale-cloud-deploy/ldap_key"
# default mm command exection path
scale_command_path: /usr/lpp/mmfs/bin/