---
galaxy_info:
  role_name: scale_ece
  author: IBM Corporation
  description: Role for configuring IBM Spectrum Scale (GPFS) Erasure Code Edition configuration role
  company: IBM
  license: Apache-2.0
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags: []

dependencies: []
