---
# YUM repository installation method

#
# Configure license package installation repository
#
- name: upgrade | Get license package
  yum:
    list: gpfs.license.*
  register: package_name_version
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: Find license package
  shell:
   cmd: apt-cache show gpfs.license.*
  register: package_name
  when:
  - ansible_pkg_mgr == 'apt'

- name: upgrade | Get license package
  shell:
   cmd: zypper info gpfs.license.* | grep Name | cut -d ':' -f 2 | tr -d '[:space:]'
  register: package_name_version_zypp
  when:
    - ansible_pkg_mgr == 'zypper'

- name: upgrade | Check valid only one GPFS License (gpfs.license) RPM
  assert:
    that: package_name_version.results | selectattr("yumstate", "match", "available") | list | length >= 1
    msg: >-
      More than one GPFS License (gpfs.license) RPM found:
      "gpfs.license*{{ scale_architecture }}*"
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: upgrade | Find GPFS License package
  vars:
    gpfs_license_package: "{{ package_name_version.results|selectattr('yumstate','match','available')|map(attribute='name')|list }}"
  set_fact:
    scale_gpfs_license_package: "{{ gpfs_license_package }}"
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: upgrade | Find GPFS License package
  set_fact:
   scale_gpfs_license_package: "{{ package_name.stdout_lines.0[9:] }}"
  when:
  - ansible_pkg_mgr == 'apt'

- name: upgrade | Find GPFS License package
  set_fact:
   scale_gpfs_license_package: "{{ package_name_version_zypp.stdout }}" 
  when:
  - ansible_pkg_mgr == 'zypper'

- name: upgrade | Add GPFS license packages to list
  set_fact:
    scale_install_license_packages: "{{ scale_install_license_packages + [ item ] }}"
  with_items:
    - "{{ scale_gpfs_license_package }}"
    - gpfs.adv
    - gpfs.crypto
  when: 
    - '"gpfs.license.std" not in scale_gpfs_license_package'
    - '"gpfs.license.da" not in scale_gpfs_license_package'

- name: upgrade | Add GPFS license packages to list
  set_fact:
    scale_install_license_packages: "{{ scale_gpfs_license_package }}"
  when: "'gpfs.license.std' in scale_gpfs_license_package or  
         'gpfs.license.da' in scale_gpfs_license_package"
