---
# defaults file for precheck
## Compute RPM version from Spectrum Scale version
scale_rpmversion: "{{ scale_version | regex_replace('^([0-9.]+)\\.([0-9])$', '\\1-\\2') }}"
## Specify package extraction path and gpg key path
scale_extracted_default_path: "/usr/lpp/mmfs"
scale_extracted_path: "{{ scale_extracted_default_path }}/{{ scale_version }}"