---
- name: install | object path
  set_fact:
    scale_obj_url: 'object_rpms/rhel8/'
  when: ansible_distribution in scale_rhel_distribution and ansible_distribution_major_version == '8'

- name: install | configure object YUM repository
  yum_repository:
    name: spectrum-scale-object-rpms
    description: IBM Spectrum Scale (object RPMS)
    baseurl: "{{ scale_install_repository_url }}{{ scale_obj_url }}"
    gpgcheck: "{{ scale_install_gpgcheck }}"
    repo_gpgcheck: no
    sslverify: no
    state: present
  notify: yum-clean-metadata
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - scale_install_repository_url is defined
    - scale_install_repository_url != 'existing'

- name: install | Add GPFS object packages to list
  set_fact:
    scale_install_all_packages: "{{ scale_install_all_packages + [ item ] }}"
  with_items:
    - "{{ scale_object_rpms }}"
  when: ansible_distribution in scale_rhel_distribution
