---
galaxy_info:
  author: IBM Corporation
  description: Role for installing IBM Spectrum Scale (GPFS) AFM COS package
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags: []

dependencies:
  - core/common
