---
#
# Install or update packages
#
- block:
    - name: install | Install GPFS gnr packages
      package:
        name: "{{ scale_install_all_packages }}"
        state: present
      when: scale_install_repository_url is defined

    - name: install | Install GPFS gnr packages
      apt:
        deb: "{{ item }}"
        state: present
      with_items:
        - "{{ scale_install_all_packages }}"
      when: scale_install_repository_url is not defined
