---

# Install or update RPMs
# Ensure that installation method was chosen during previous role
- block:
  - name: upgrade | Check for repository installation method
    set_fact:
     scale_installmethod: repository
    when:
    - scale_install_repository_url is defined

  - name: upgrade | Check for localpkg installation method
    set_fact:
     scale_installmethod: local_pkg
    when:
    - scale_install_repository_url is undefined
    - scale_install_remotepkg_path is undefined
    - scale_install_localpkg_path is defined

  - name: upgrade | Check for remotepkg installation method
    set_fact:
     scale_installmethod: remote_pkg
    when:
    - scale_install_repository_url is undefined
    - scale_install_remotepkg_path is defined

  - name: upgrade | Check for directory package installation method
    set_fact:
      scale_installmethod: dir_pkg
    when:
      - scale_install_repository_url is undefined
      - scale_install_remotepkg_path is undefined
      - scale_install_localpkg_path is undefined
      - scale_install_directory_pkg_path is defined

  - name: upgrade | Check installation method
    assert:
     that: scale_installmethod is defined
     msg: >-
          Please set the appropriate variable 'scale_upgrade_*' for your desired
          installation method!
  run_once: true
  delegate_to: localhost

# Run chosen installation method to get list of RPMs

- name: upgrade | Initialize list of packages
  set_fact:
   scale_upgrade_all_packages: []

- name: upgrade | Set the extracted package directory path
  set_fact:
    hdfs_extracted_path: "{{ scale_extracted_path }}"
    hdfs_version_path_selection_rhel: "{{ scale_hdfs_rhel_version_path }}"

- name: upgrade | Stat extracted packages directory
  stat:
    path: "{{ hdfs_extracted_path }}"
  register: scale_extracted_gpfs_dir

- include_tasks: prepare_env.yml

- block:
  - name:
    set_fact:
       hdfs_version_path_selection_rhel: "{{ scale_hdfs_rhel_version_path_33 }}"
    when: transparency_33_enabled|bool

  - name:
    set_fact:
       hdfs_version_path_selection_rhel: "{{ scale_hdfs_rhel_version_path_322 }}"
    when: transparency_322_enabled|bool

  - name: upgrade | Fetch hdfs rpm dir path for rhel
    set_fact:
        hdfs_rpm_path_rhel: "{{ hdfs_version_path_selection_rhel }}"
  run_once: true
  delegate_to: localhost

- include_tasks: upgrade_{{ scale_installmethod }}.yml

- import_tasks: yum/upgrade.yml
  when: ansible_distribution in scale_rhel_distribution
