---
# Default variables for the IBM Spectrum Scale (GPFS) Grafana role -
# either edit this file or define your own variables to override the defaults

## Specify the URL of the (existing) Spectrum Scale GPFS YUM repository
## (copy the contents of /usr/lpp/mmfs/.../gpfs_rpms/ to build your repository)
# scale_install_repository_url: http://infraserv/

## Note that if this is a URL then a new repository definition will be created.
## If this variable is set to 'existing' then it is assumed that a repository
## definition already exists and thus will *not* be created.

## Specify the Spectrum Scale architecture that you want to install on your nodes
scale_architecture: "{{ ansible_architecture }}"

## List of RPMs to install on collector nodes
scale_grafana_packages:
  - gpfs.grafana-bridge

## you'll likely want to define per-node roles in your inventory
scale_install_package: true

## To Enabled output from Ansible task in stdout and stderr for some tasks.
## Run the playbook with -vv
