---
- name: Upgrade GPFS hdfs packages
  package:
   name: "{{ scale_install_all_packages }}"
   state: latest
  when: scale_install_repository_url is defined and ansible_fqdn in scale_hdfs_node_list


- name: upgrade| Upgrade GPFS HDFS deb
  apt:
   deb: "{{ item }}"
   state: latest
  when: scale_install_repository_url is not defined and ansible_fqdn in scale_hdfs_node_list
  with_items:
  - "{{ scale_install_all_packages }}"

